receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:3030"

processors:
  batch:

exporters:
  otlp:
    # disable tls
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging ]

